// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ImgJs       = require("./img.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function make(image, children) {
  return ReasonReact.wrapJsForReason(ImgJs.imageComponent, {
              image: image
            }, children);
}

exports.make = make;
/* ./img.js Not a pure module */
